// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Models;

namespace Test.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    partial class FlightDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Polish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Models.CityDict", b =>
                {
                    b.Property<int>("IdCityDict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdCityDict")
                        .HasName("CityDict_pk");

                    b.ToTable("CityDict");

                    b.HasData(
                        new
                        {
                            IdCityDict = 1,
                            City = "Warsaw"
                        },
                        new
                        {
                            IdCityDict = 2,
                            City = "Berlin"
                        });
                });

            modelBuilder.Entity("Test.Models.Flight", b =>
                {
                    b.Property<int>("IdFlight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCItyDict")
                        .HasColumnType("int");

                    b.Property<int>("IdPlane")
                        .HasColumnType("int");

                    b.HasKey("IdFlight")
                        .HasName("Flight_pk");

                    b.HasIndex("IdCItyDict");

                    b.HasIndex("IdPlane");

                    b.ToTable("Flight");

                    b.HasData(
                        new
                        {
                            IdFlight = 1,
                            Comment = "default",
                            FlightDate = new DateTime(2021, 5, 13, 10, 49, 20, 654, DateTimeKind.Local).AddTicks(6515),
                            IdCItyDict = 2,
                            IdPlane = 1
                        });
                });

            modelBuilder.Entity("Test.Models.Flight_Passenger", b =>
                {
                    b.Property<int>("IdFlight")
                        .HasColumnType("int");

                    b.Property<int>("IdPassenger")
                        .HasColumnType("int");

                    b.HasKey("IdFlight", "IdPassenger")
                        .HasName("Flight_Passenger_pk");

                    b.HasIndex("IdPassenger");

                    b.ToTable("Flight_Passenger");

                    b.HasData(
                        new
                        {
                            IdFlight = 1,
                            IdPassenger = 1
                        },
                        new
                        {
                            IdFlight = 1,
                            IdPassenger = 2
                        });
                });

            modelBuilder.Entity("Test.Models.Passenger", b =>
                {
                    b.Property<int>("IdPassenger")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PassportNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdPassenger")
                        .HasName("Passenger_pk");

                    b.ToTable("Passenger");

                    b.HasData(
                        new
                        {
                            IdPassenger = 1,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            PassportNum = "1234567890"
                        },
                        new
                        {
                            IdPassenger = 2,
                            FirstName = "Tom",
                            LastName = "Reddle",
                            PassportNum = "551662883"
                        });
                });

            modelBuilder.Entity("Test.Models.Plane", b =>
                {
                    b.Property<int>("IdPlane")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxSeats")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPlane")
                        .HasName("Plane_pk");

                    b.ToTable("Plane");

                    b.HasData(
                        new
                        {
                            IdPlane = 1,
                            MaxSeats = 150,
                            Name = "Jet321"
                        },
                        new
                        {
                            IdPlane = 2,
                            MaxSeats = 250,
                            Name = "Boeng456"
                        });
                });

            modelBuilder.Entity("Test.Models.Flight", b =>
                {
                    b.HasOne("Test.Models.CityDict", "IdCityDictNavigation")
                        .WithMany("Flights")
                        .HasForeignKey("IdCItyDict")
                        .HasConstraintName("Flight_CityDict")
                        .IsRequired();

                    b.HasOne("Test.Models.Plane", "IdPlaneNavigation")
                        .WithMany("Flights")
                        .HasForeignKey("IdPlane")
                        .HasConstraintName("Flight_Plane")
                        .IsRequired();

                    b.Navigation("IdCityDictNavigation");

                    b.Navigation("IdPlaneNavigation");
                });

            modelBuilder.Entity("Test.Models.Flight_Passenger", b =>
                {
                    b.HasOne("Test.Models.Flight", "IdFlightNavigation")
                        .WithMany("Flight_Passengers")
                        .HasForeignKey("IdFlight")
                        .HasConstraintName("Flight_Passenger_Flight")
                        .IsRequired();

                    b.HasOne("Test.Models.Passenger", "IdPassengerNavigation")
                        .WithMany("Flight_Passengers")
                        .HasForeignKey("IdPassenger")
                        .HasConstraintName("Flight_Passenger_Passenger")
                        .IsRequired();

                    b.Navigation("IdFlightNavigation");

                    b.Navigation("IdPassengerNavigation");
                });

            modelBuilder.Entity("Test.Models.CityDict", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Test.Models.Flight", b =>
                {
                    b.Navigation("Flight_Passengers");
                });

            modelBuilder.Entity("Test.Models.Passenger", b =>
                {
                    b.Navigation("Flight_Passengers");
                });

            modelBuilder.Entity("Test.Models.Plane", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
